package com.edlplan.osu.support.timing.controlpoint

import com.edlplan.osu.support.timing.TimingPoint
import com.edlplan.osu.support.timing.TimingPoints
import java.util.ArrayList
import java.util.Collections

class ControlPoints {
    private val timingPoints = ArrayList<TimingControlPoint>()
    private val difficultyPoints = ArrayList<DifficultyControlPoint>()
    private val effectPoints = ArrayList<EffectControlPoint>()
    private val samplePoints = ArrayList<SampleControlPoint>()

    fun load(points: TimingPoints) {
        val res = points.getTimingPointList()
        if (res.size < 1) {
            throw IllegalArgumentException("a beatmap must has at least 1 timing point")
        }

        var tmpIndex = -1
        for (i in res.indices) {
            if (!res[i].inherited) {
                tmpIndex = i
                break
            }
        }

        val tmp: TimingPoint = if (tmpIndex == -1) {
            val tp = TimingPoint()
            tp.time = 0.0
            tp.beatLength = 1000.0
            tp.meter = 4
            tp
        } else {
            res[tmpIndex]
        }

        var preTp = TimingControlPoint()
        preTp.time = tmp.time
        preTp.beatLength = tmp.beatLength
        preTp.meter = tmp.meter
        timingPoints.add(preTp)

        val firstTp = res[0]
        var preDcp = DifficultyControlPoint()
        preDcp.time = firstTp.time
        preDcp.speedMultiplier = firstTp.speedMultiplier
        difficultyPoints.add(preDcp)

        var preScp = SampleControlPoint()
        preScp.time = firstTp.time
        samplePoints.add(preScp)

        var preEcp = EffectControlPoint()
        preEcp.time = firstTp.time
        preEcp.kiaiModeOn = firstTp.kiaiMode
        preEcp.omitFirstBarLine = firstTp.omitFirstBarSignature
        effectPoints.add(preEcp)

        for (i in res.indices) {
            val t = res[i]
            if (!t.inherited) {
                preTp = TimingControlPoint()
                preTp.time = t.time
                preTp.beatLength = t.beatLength
                preTp.meter = t.meter
                timingPoints.add(preTp)
            }

            if (preDcp.speedMultiplier != t.speedMultiplier) {
                if (preDcp.time == t.time) {
                    if (t.inherited) {
                        difficultyPoints.remove(preDcp)
                        preDcp = DifficultyControlPoint()
                        preDcp.time = t.time
                        preDcp.speedMultiplier = t.speedMultiplier
                        preDcp.autoGenerated = t.inherited
                        difficultyPoints.add(preDcp)
                    }
                } else {
                    preDcp = DifficultyControlPoint()
                    preDcp.time = t.time
                    preDcp.speedMultiplier = t.speedMultiplier
                    preDcp.autoGenerated = t.inherited
                    difficultyPoints.add(preDcp)
                }
            }

            if (t.kiaiMode != preEcp.kiaiModeOn || t.omitFirstBarSignature != preEcp.omitFirstBarLine) {
                preEcp = EffectControlPoint()
                preEcp.time = t.time
                preEcp.kiaiModeOn = t.kiaiMode
                preEcp.omitFirstBarLine = t.omitFirstBarSignature
                effectPoints.add(preEcp)
            }
        }
        Collections.sort(timingPoints) { a, b -> java.lang.Double.compare(a.time, b.time) }
        Collections.sort(difficultyPoints) { a, b -> java.lang.Double.compare(a.time, b.time) }
        Collections.sort(effectPoints) { a, b -> java.lang.Double.compare(a.time, b.time) }
    }

    private fun handleDifficultyControlPoint(newPoint: DifficultyControlPoint) {
        val existing = getDifficultyPointAt(newPoint.time)

        if (existing.time == newPoint.time) {
            if (newPoint.autoGenerated && !existing.autoGenerated) return

            difficultyPoints.remove(existing)
        }

        difficultyPoints.add(newPoint)
        Collections.sort(difficultyPoints) { a, b -> java.lang.Double.compare(a.time, b.time) }
    }

    fun getTimingPointAt(time: Double): TimingControlPoint? {
        if (timingPoints.isEmpty()) return null
        return binarySearch(timingPoints, time, timingPoints[0])
    }

    fun getEffectPointAt(time: Double): EffectControlPoint? {
        if (effectPoints.isEmpty()) return null
        return binarySearch(effectPoints, time, effectPoints[0])
    }

    fun getSamplePointAt(time: Double): SampleControlPoint? {
        if (samplePoints.isEmpty()) return null
        return binarySearch(samplePoints, time, samplePoints[0])
    }

    fun getDifficultyPointAt(time: Double): DifficultyControlPoint {
        if (difficultyPoints.isEmpty()) return defaultDifficultyPoint
        val difficultyControlPoint = binarySearch(difficultyPoints, time, defaultDifficultyPoint)
        return difficultyControlPoint ?: defaultDifficultyPoint
    }

    private fun <T : ControlPoint> binarySearch(list: List<T>, time: Double, prePoint: T): T? {
        if (list.isEmpty()) return null

        if (time < list[0].time) return prePoint

        if (time >= list[list.size - 1].time) return list[list.size - 1]

        var l = 0
        var r = list.size - 2

        while (l <= r) {
            val pivot = l + ((r - l) shr 1)

            if (list[pivot].time < time) {
                l = pivot + 1
            } else if (list[pivot].time > time) {
                r = pivot - 1
            } else {
                return list[pivot]
            }
        }

        return list[l - 1]
    }

    companion object {
        private val defaultDifficultyPoint = DifficultyControlPoint().apply {
            speedMultiplier = 1.0
        }
    }
}
